spring:
  datasource:
    url: jdbc:h2:mem:libdb;IGNORECASE=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: schema.sql
    data: data.sql

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none